version: "3"
services:
  database:
    image: "docker.pkg.github.com/rcopstein/open-store-database/database:latest"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PORT=${DATABASE_PORT}
      - PGDATA=${PGDATA}
    volumes:
      - database_data:${PGDATA}:rw
    restart: always
    expose:
      - ${DATABASE_PORT}:5432
  api:
    image: "docker.pkg.github.com/rcopstein/open-store-server/server:develop"
    environment:
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - NODE_ENV=${NODE_ENV}
      - PORT=${SERVER_PORT}
      - PGHOST=${PGHOST}
      - PGUSER=${PGUSER}
      - PGPORT=${PGPORT}
    restart: always
    ports:
      - ${SERVER_PORT}:1801
  client:
    image: "docker.pkg.github.com/rcopstein/open-store-client/client:latest"
    restart: always
    ports:
      - ${CLIENT_PORT}:80

volumes:
  database_data:
